server {
    listen 80;
    server_name dev.sbamsr.irk.ru 84.237.24.66;

    # Игнорируем иконку сайта (чтобы не спамить в логи)
    location = /favicon.ico { access_log off; log_not_found off; }

    # Путь к собранной статике (результат collectstatic)
    location /static/ {
        alias /var/www/Chronic-Endometritis-Application/staticfiles/;
    }

    # Передача всех остальных запросов в Django
    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/Chronic-Endometritis-Application/app.sock;
    }

    # Настройки безопасности (необязательно, но полезно)
    client_max_body_size 20M;
}